# Generated by Django 4.2.10 on 2026-01-17 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ESTIMATED', 'Estimated'), ('PAID', 'Paid'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='request_attachments/')),
                ('uploaded_by', models.CharField(choices=[('USER', 'User Upload'), ('ADMIN', 'Admin Upload')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='requests_app.projectrequest')),
            ],
        ),
    ]
