# Generated by Django 6.0.1 on 2026-01-30 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_theme_alter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='theme',
            new_name='profile_theme',
        ),
    ]
